parallella/fpga: hdmi z7010: Try fixing clock implementation error
Apparently axi_dmac uses more resources than axi_vdma did.

Relax clk_wiz_0 (used by SPDIF) as much as possible. No buffers on input
or output.

Unfortunately implementation still errors out because of block-RAM
over-utilization:

Phase 1.2 IO Placement/ Clock Placement/ Build Placer Device
ERROR: [Place 30-640] Place Check : This design requires more RAMB18 and
RAMB36/FIFO cells than are available in the target device. This design
requires 121 of such cell types but only 120 compatible sites are
available in the target device. Please analyze your synthesis results
and constraints to ensure the design is mapped to Xilinx primitives as
expected. If so, please consider targeting a larger device.
INFO: [Timing 38-35] Done setting XDC timing constraints.
Phase 1.2 IO Placement/ Clock Placement/ Build Placer Device | Checksum: 43b4e0ea